default:
	gcc Node_LOGIC.c LoadDT.c PaintTable.c Write_dataB.c functionhleperstr.c Score_LOGIC.c Read_dataB.c Load_input.c Show_Table.c main.c -o myprogram
	x86_64-w64-mingw32-gcc Node_LOGIC.c LoadDT.c PaintTable.c Write_dataB.c functionhleperstr.c Score_LOGIC.c Read_dataB.c Load_input.c Show_Table.c main.c -o myprogram.exe