#include "const_value.h"

const char courses_IT[][MAX_LENGTH] = {
    "> IT1108 = Introduction_to_Programming",
    "> IT2000 = Introduction_to_IT_and_Communications",
    "> IT3080 = Computer_Networks",
    "> IT3030 = Computer_Architecture",
    "> IT3011 = Data_Structures_and_Algorithms",
    "> IT3020 = Discrete_Mathematics",
    "> IT3070 = Applied_Algorithms",
    "> IT3100 = Object-Oriented_Programming",
    "> IT3090 = Database_Systems",
    "> IT3170 = Applied_Algorithms",
    "> IT3150 = Project_I",
    "> IT3040 = Programming_Techniques",
    "> IT3160 = Introduction_to_Artificial_Intelligence",
    "> IT3180 = Introduction_to_Software_Engineering",
    "> IT3120 = System_Analysis_and_Design",
    "> IT3190 = Introduction_to_Machine_Learning_and_Data_Mining",
    "> IT4015 = Introduction_to_Information_Security",
    "> IT4991 = Technical_Internship",
    "> IT3930 = Project_II",
    "> IT4653 = Deep_Learning_and_Its_Applications",
    "> IT4788 = Cross-Platform_Application_Development",
    "> IT4785 = Mobile_Application_Development",
    "> IT4441 = User_Interface_and_User_Experience",
    "> IT4409 = Web_Technology_and_Online_Services",
    "> IT4490 = Software_Design_and_Construction",
    "> IT4501 = Software_Quality_Assurance",
    "> IT3940 = Project_III",
    "> IT4995 = Bachelor's_Graduation_Project"
};